from collections.abc import Iterable
from itertools import chain


def solution() -> int:
    """Return the largest palindrome that can be made from the product of 2 3-digit numbers."""
    for palindrome in get_palindromes():
        if is_product(palindrome):
            return palindrome
    return 0


def get_palindromes() -> Iterable[int]:
    """Generates palindromes that can potentially be generated by the product of 2 3-digit numbers."""
    return chain(
        (
            i * 100001 + j * 10010 + k * 1100
            for i in range(9, 0, -1)
            for j in range(9, -1, -1)
            for k in range(9, -1, -1)
        ),
        (
            i * 10001 + j * 1010 + k * 100
            for i in range(9, 0, -1)
            for j in range(9, -1, -1)
            for k in range(9, -1, -1)
        ),
    )


def is_product(x: int) -> bool:
    """Returns if x = a x b where a and b are 3-digit numbers."""
    for a in range(100, min(1000, int(x**0.5) + 1)):
        if x % a == 0 and 100 <= x // a < 1000:
            return True
    return False


if __name__ == "__main__":
    result = solution()
    print(
        f"The largest palindrome that can be made from the product of 2 3-digit numbers is {result}"
    )
